title: Raider Robotics

username: Raider Robotics
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: SProgramming Team
email: anon@anon.com
github_username:  frc5024

remote_theme: nrandecker/particle
